"""empty message

Revision ID: 2361171c787f
Revises: 
Create Date: 2019-08-05 16:34:30.391708

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2361171c787f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meetups',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('created_at', sa.DateTime(),
                              server_default=sa.text('now()'), nullable=True),
                    sa.Column('updated_at', sa.DateTime(),
                              server_default=sa.text('now()'), nullable=True),
                    sa.Column('topic', sa.String(length=250), nullable=False),
                    sa.Column('location', sa.String(
                        length=100), nullable=False),
                    sa.Column('happening_on', sa.DateTime(), nullable=False),
                    sa.Column('images', postgresql.ARRAY(
                        sa.String()), nullable=True),
                    sa.Column('tags', postgresql.ARRAY(
                        sa.String(length=100)), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('users',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('created_at', sa.DateTime(),
                              server_default=sa.text('now()'), nullable=True),
                    sa.Column('updated_at', sa.DateTime(),
                              server_default=sa.text('now()'), nullable=True),
                    sa.Column('firstname', sa.String(
                        length=100), nullable=False),
                    sa.Column('lastname', sa.String(
                        length=100), nullable=False),
                    sa.Column('othername', sa.String(
                        length=100), nullable=True),
                    sa.Column('email', sa.String(length=100), nullable=False),
                    sa.Column('password', sa.String(
                        length=250), nullable=False),
                    sa.Column('is_admin', sa.Boolean(), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('email')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('meetups')
    # ### end Alembic commands ###
