"""empty message

Revision ID: 455c7058d506
Revises: 
Create Date: 2019-07-18 14:24:10.048196

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '455c7058d506'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('firstname', sa.String(
                        length=100), nullable=False),
                    sa.Column('lastname', sa.String(
                        length=100), nullable=False),
                    sa.Column('othername', sa.String(
                        length=100), nullable=True),
                    sa.Column('email', sa.String(length=100), nullable=False),
                    sa.Column('password', sa.String(
                        length=250), nullable=False),
                    sa.Column('is_admin', sa.Boolean(), nullable=False),
                    sa.Column('created_at', sa.DateTime(),
                              server_default=sa.text('now()'), nullable=True),
                    sa.Column('updated_at', sa.DateTime(),
                              server_default=sa.text('now()'), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('email')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
