"""empty message

Revision ID: cdc6f768a706
Revises: 0e26bbfe088a
Create Date: 2019-09-05 09:05:07.829380

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cdc6f768a706'
down_revision = '0e26bbfe088a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'title')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('title', sa.VARCHAR(length=250), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
